-- MySQL Script generated by MySQL Workbench
-- Wed May 22 03:23:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema englishworkout
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `englishworkout` ;

-- -----------------------------------------------------
-- Schema englishworkout
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `englishworkout` DEFAULT CHARACTER SET utf8 ;
USE `englishworkout` ;

-- -----------------------------------------------------
-- Table `englishworkout`.`category_sentence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`category_sentence` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`category_sentence` (
  `idcategorysentence` INT NOT NULL AUTO_INCREMENT,
  `namecategory` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorysentence`),
  UNIQUE INDEX `idcategory_sentence_UNIQUE` (`idcategorysentence` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `englishworkout`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`language` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`language` (
  `idlanguage` INT NOT NULL AUTO_INCREMENT,
  `namelanguage` VARCHAR(45) NULL,
  PRIMARY KEY (`idlanguage`),
  UNIQUE INDEX `idlanguage_UNIQUE` (`idlanguage` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `englishworkout`.`typesentence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`typesentence` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`typesentence` (
  `idtypesentence` INT NOT NULL AUTO_INCREMENT,
  `nametypesentencecol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtypesentence`),
  UNIQUE INDEX `idtypesentence_UNIQUE` (`idtypesentence` ASC) VISIBLE,
  UNIQUE INDEX `nametypesentencecol_UNIQUE` (`nametypesentencecol` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `englishworkout`.`sentence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`sentence` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`sentence` (
  `IdSentence` INT NOT NULL AUTO_INCREMENT,
  `sentence` VARCHAR(300) NOT NULL,
  `tipssentence` VARCHAR(300) NULL,
  `IdCategorySentence` INT NOT NULL,
  `idlanguage` INT NOT NULL,
  `idtypesentence` INT NOT NULL,
  INDEX `fk_sentences_category_sentence_idx` (`IdCategorySentence` ASC) VISIBLE,
  INDEX `fk_sentences_source_language1_idx` (`idlanguage` ASC) VISIBLE,
  PRIMARY KEY (`IdSentence`),
  INDEX `fk_sentence_typesentence1_idx` (`idtypesentence` ASC) VISIBLE,
  CONSTRAINT `fk_sentences_category_sentence`
    FOREIGN KEY (`IdCategorySentence`)
    REFERENCES `englishworkout`.`category_sentence` (`idcategorysentence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sentences_source_language1`
    FOREIGN KEY (`idlanguage`)
    REFERENCES `englishworkout`.`language` (`idlanguage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sentence_typesentence1`
    FOREIGN KEY (`idtypesentence`)
    REFERENCES `englishworkout`.`typesentence` (`idtypesentence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `englishworkout`.`typetest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`typetest` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`typetest` (
  `idtypetest` INT NOT NULL,
  `typename` VARCHAR(200) NULL,
  PRIMARY KEY (`idtypetest`),
  UNIQUE INDEX `idtypetest_UNIQUE` (`idtypetest` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `englishworkout`.`sentencetest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`sentencetest` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`sentencetest` (
  `idsentencetest` INT NOT NULL AUTO_INCREMENT,
  `nametest` VARCHAR(45) NULL,
  `dateinic` DATETIME NULL,
  `datefim` DATETIME NULL,
  `accurate` INT NULL,
  `mistake` INT NULL,
  `typetest_idtypetest` INT NOT NULL,
  `idlanguagesource` INT NULL,
  `idlanguagetranslate` INT NULL,
  `idcategorysentence` INT NOT NULL,
  PRIMARY KEY (`idsentencetest`),
  INDEX `fk_sentencetest_typetest1_idx` (`typetest_idtypetest` ASC) VISIBLE,
  INDEX `fk_sentencetest_category_sentence1_idx` (`idcategorysentence` ASC) VISIBLE,
  UNIQUE INDEX `idsentencetest_UNIQUE` (`idsentencetest` ASC) VISIBLE,
  CONSTRAINT `fk_sentencetest_typetest1`
    FOREIGN KEY (`typetest_idtypetest`)
    REFERENCES `englishworkout`.`typetest` (`idtypetest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sentencetest_category_sentence1`
    FOREIGN KEY (`idcategorysentence`)
    REFERENCES `englishworkout`.`category_sentence` (`idcategorysentence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `englishworkout`.`relsourcetranslate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`relsourcetranslate` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`relsourcetranslate` (
  `idrelsourcetranslate` INT NOT NULL AUTO_INCREMENT,
  `idsentencetranslate` INT NOT NULL,
  `idsentencesource` INT NOT NULL,
  PRIMARY KEY (`idrelsourcetranslate`),
  UNIQUE INDEX `idrelsourcetranslate_UNIQUE` (`idrelsourcetranslate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `englishworkout`.`itemsentencetest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `englishworkout`.`itemsentencetest` ;

CREATE TABLE IF NOT EXISTS `englishworkout`.`itemsentencetest` (
  `iditemusersentence` INT NOT NULL AUTO_INCREMENT,
  `sentenceusertranslate` VARCHAR(300) NULL,
  `resulttestsentence` INT NULL,
  `idsentencetest` INT NOT NULL,
  `idrelsourcetranslate` INT NOT NULL,
  PRIMARY KEY (`iditemusersentence`),
  INDEX `fk_itemsentencetest_sentencetest1_idx` (`idsentencetest` ASC) VISIBLE,
  UNIQUE INDEX `iditemusersentence_UNIQUE` (`iditemusersentence` ASC) VISIBLE,
  INDEX `fk_itemsentencetest_relsourcetranslate1_idx` (`idrelsourcetranslate` ASC) VISIBLE,
  CONSTRAINT `fk_itemsentencetest_sentencetest1`
    FOREIGN KEY (`idsentencetest`)
    REFERENCES `englishworkout`.`sentencetest` (`idsentencetest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemsentencetest_relsourcetranslate1`
    FOREIGN KEY (`idrelsourcetranslate`)
    REFERENCES `englishworkout`.`relsourcetranslate` (`idrelsourcetranslate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `englishworkout`.`category_sentence`
-- -----------------------------------------------------
START TRANSACTION;
USE `englishworkout`;

INSERT INTO `englishworkout`.`category_sentence` (`idcategorysentence`, `namecategory`) VALUES (01, 'Present');
INSERT INTO `englishworkout`.`category_sentence` (`idcategorysentence`, `namecategory`) VALUES (02, 'Simple past');
INSERT INTO `englishworkout`.`category_sentence` (`idcategorysentence`, `namecategory`) VALUES (03, 'Past participle');
INSERT INTO `englishworkout`.`category_sentence` (`idcategorysentence`, `namecategory`) VALUES (04, 'Future');
INSERT INTO `englishworkout`.`category_sentence` (`idcategorysentence`, `namecategory`) VALUES (05, 'Past of will');
INSERT INTO `englishworkout`.`category_sentence` (`idcategorysentence`, `namecategory`) VALUES (06, 'Past of shall');
INSERT INTO `englishworkout`.`category_sentence` (`idcategorysentence`, `namecategory`) VALUES (07, 'Past of can');

COMMIT;


-- -----------------------------------------------------
-- Data for table `englishworkout`.`language`
-- -----------------------------------------------------
START TRANSACTION;
USE `englishworkout`;
INSERT INTO `englishworkout`.`language` (`idlanguage`, `namelanguage`) VALUES (01, 'Portuguese');
INSERT INTO `englishworkout`.`language` (`idlanguage`, `namelanguage`) VALUES (02, 'English');

COMMIT;


-- -----------------------------------------------------
-- Data for table `englishworkout`.`typesentence`
-- -----------------------------------------------------
START TRANSACTION;
USE `englishworkout`;
INSERT INTO `englishworkout`.`typesentence` (`idtypesentence`, `nametypesentencecol`) VALUES (1, 'Afirmação');
INSERT INTO `englishworkout`.`typesentence` (`idtypesentence`, `nametypesentencecol`) VALUES (2, 'Negação');
INSERT INTO `englishworkout`.`typesentence` (`idtypesentence`, `nametypesentencecol`) VALUES (3, 'Interrogação');

COMMIT;


-- -----------------------------------------------------
-- Data for table `englishworkout`.`typetest`
-- -----------------------------------------------------
START TRANSACTION;
USE `englishworkout`;
INSERT INTO `englishworkout`.`typetest` (`idtypetest`, `typename`) VALUES (01, 'Portuguese to English');
INSERT INTO `englishworkout`.`typetest` (`idtypetest`, `typename`) VALUES (02, 'English to Portuguese');

COMMIT;

